Windows builds and small fixes
alexhude/LoadProcConfig pull request #1
Opened 2017-06-09 22:55 UTC by four0four

- fixed crash when no config file is selected
- normalized to UNIX line endings
- added windows vc15 configs
- added windows binaries

Just a few misc things :)

2017-06-10 23:35 UTC, alexhude requested changes
Awesome PR! Thanks for line endings, no idea how this happened :)
Just fix this tiny bit and I will merge it.

2017-06-10 23:35 UTC, alexhude commented on LoadProcConfig/LoadProcConfig.cpp
> +	char dir_up[] "../";
missed '='

2017-06-11 00:46 UTC, merged

2017-06-11 00:46 UTC, alexhude commented
Merged! Thanks, mate.

2017-06-11 00:47 UTC, four0four commented
You can tell what platforms I run IDA on...

No problem! Thanks for writing the tool I've been meaning to :)